[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements-production.txt"]

[phases.build]
cmds = []

[start]
cmd = "uvicorn api_chatbot:app --host 0.0.0.0 --port $PORT"

